# ============================================
# IHSG STOCKS LIST - FULL COMPREHENSIVE
# ============================================
# Format: Yahoo Finance ticker with .JK suffix

IHSG_STOCKS = [
    # === EXISTING USER REQUESTED (PRIORITY) ===
    "BUMI.JK", "DEWA.JK", "ANTM.JK", "BBCA.JK", "BBRI.JK",
    "BMRI.JK", "BRMS.JK", "INET.JK", "PTRO.JK", "ADRO.JK",
    "RAJA.JK", "ARCI.JK", "SUPA.JK", "BUVA.JK", "BULL.JK",
    "GOTO.JK", "MINA.JK", "MBMA.JK", "ASII.JK", "TLKM.JK",
    "AMMN.JK", "MDKA.JK", "BRPT.JK", "INCO.JK", "DSSA.JK",
    "TINS.JK", "BKSL.JK", "BBNI.JK", "UNTR.JK", "WIFI.JK",
    "CDIA.JK", "NCKL.JK", "IMPC.JK", "ENRG.JK", "RATU.JK",
    "ADMR.JK", "PANI.JK", "CUAN.JK", "EMAS.JK", "INDY.JK",
    "GTSI.JK", "HRTA.JK", "BIPI.JK", "KIJA.JK", "RMKE.JK",
    "HUMI.JK", "MEDC.JK", "CBDK.JK", "NICL.JK", "COIN.JK",
    "OASA.JK", "EMTK.JK", "EXCL.JK", "BREN.JK", "JPFA.JK",
    "TOBA.JK", "PNLF.JK", "INKP.JK", "VKTR.JK", "PSAB.JK",
    "PADI.JK", "TCPI.JK", "AADI.JK", "PWON.JK", "PGAS.JK",
    "RLCO.JK", "BBYB.JK", "CPRO.JK", "HRUM.JK", "TRIN.JK",
    "UNVR.JK", "INDF.JK", "LEAD.JK", "TRUE.JK", "ITMA.JK",
    "PSKT.JK", "SMDR.JK", "KLBF.JK", "ICBP.JK", "SSIA.JK",
    "BBKP.JK", "PGEO.JK", "KETR.JK", "BRIS.JK", "SINI.JK",
    "AMRT.JK", "IRSX.JK", "LPKR.JK", "TPIA.JK", "PADA.JK",
    "NRCA.JK", "SCMA.JK", "COAL.JK", "ZATA.JK", "IATA.JK",
    "DKFT.JK", "BNBR.JK", "SOCI.JK", "ISAT.JK", "ELTY.JK",
    "REAL.JK", "PTBA.JK", "PBSA.JK", "PIPA.JK", "PPRE.JK",
    "KPIG.JK", "SMIL.JK", "CPIN.JK", "PJHB.JK", "ESSA.JK",
    "HMSP.JK", "BBTN.JK", "SRTG.JK", "TEBE.JK", "FILM.JK",
    "TOWR.JK", "DOOH.JK", "DATA.JK", "AKRA.JK", "CTRA.JK",
    "DSNG.JK", "SMGR.JK", "MBSS.JK", "MORA.JK", "MHKI.JK",
    "FUTR.JK", "INPC.JK", "ITMG.JK", "MAPI.JK", "GOLF.JK",
    "SGER.JK", "ASLI.JK", "ASHA.JK", "AHAP.JK", "CBRE.JK",
    "CYBR.JK", "JARR.JK", "MLPL.JK", "PTPP.JK", "SMRA.JK",
    "GGRM.JK", "BWPT.JK", "MYOR.JK", "MTEL.JK", "ELIT.JK",
    "JSMR.JK", "CMNT.JK", "ARKO.JK", "BUKA.JK", "VICI.JK",
    "TBIG.JK", "ELSA.JK", "FOLK.JK", "MEJA.JK", "WIRG.JK",
    "MAHA.JK", "BELL.JK", "MSIN.JK", "NETV.JK", "TAPG.JK",
    "INDO.JK", "ASRI.JK", "TOSK.JK", "KLAS.JK", "DAAZ.JK",
    "KEEN.JK", "NINE.JK", "PNBN.JK", "OPMS.JK", "BBRM.JK",
    "MARK.JK", "FIRE.JK", "UNIQ.JK", "AYAM.JK", "STRK.JK",
    "FAST.JK", "PACK.JK", "BMTR.JK", "TMAS.JK", "BACA.JK",
    "ERAA.JK", "BSDE.JK", "COCO.JK", "DMAS.JK", "TRON.JK",
    "SLIS.JK", "PYFA.JK", "TKIM.JK", "KDTN.JK", "ARTO.JK",
    "SOLA.JK", "KRAS.JK", "SGRO.JK", "MAPA.JK", "APEX.JK",
    "NSSS.JK", "DSFI.JK", "KOCI.JK", "BSBK.JK", "GIAA.JK",
    "GMFI.JK", "SMGA.JK", "INTP.JK", "UANG.JK", "HOPE.JK",
    "WIIM.JK", "SMKM.JK", "ASSA.JK", "IKAN.JK", "BGTG.JK",
    "BOAT.JK", "FPNI.JK", "HATM.JK", "JGLE.JK", "RMKO.JK",
    "HDIT.JK", "DEWI.JK", "KOKA.JK", "WOWS.JK", "ATLA.JK",
    "ACES.JK", "MNCN.JK", "MSKY.JK", "BEEF.JK", "IMJS.JK",
    "BFIN.JK", "UDNG.JK", "CMRY.JK", "ERAL.JK", "MMIX.JK",
    "JAST.JK",

    # === NEW ADDITIONS (426 stocks) ===
    "AALI.JK", "ABMM.JK", "ACRO.JK", "ACST.JK", "ADES.JK",
    "ADHI.JK", "ADMF.JK", "ADMG.JK", "AEGS.JK", "AGAR.JK",
    "AGII.JK", "AGRO.JK", "AGRS.JK", "AIMS.JK", "AISA.JK",
    "AKPI.JK", "ALDO.JK", "ALII.JK", "ALKA.JK", "AMAN.JK",
    "AMIN.JK", "AMMS.JK", "AMOR.JK", "ANJT.JK", "APIC.JK",
    "APII.JK", "APLI.JK", "APLN.JK", "AREA.JK", "ARGO.JK",
    "ARNA.JK", "ASDM.JK", "ASGR.JK", "ASJT.JK", "ASLC.JK",
    "ASPI.JK", "ASPR.JK", "ASRM.JK", "ATIC.JK", "AUTO.JK",
    "AVIA.JK", "AWAN.JK", "AYLS.JK", "BABP.JK", "BABY.JK",
    "BAIK.JK", "BAJA.JK", "BALI.JK", "BANK.JK", "BAPA.JK",
    "BATR.JK", "BAYU.JK", "BBHI.JK", "BBLD.JK", "BBMD.JK",
    "BBSI.JK", "BBSS.JK", "BCAP.JK", "BCIC.JK", "BCIP.JK",
    "BDKR.JK", "BDMN.JK", "BEER.JK", "BESS.JK", "BEST.JK",
    "BHAT.JK", "BIKE.JK", "BINA.JK", "BIRD.JK", "BJBR.JK",
    "BJTM.JK", "BKSW.JK", "BLES.JK", "BLOG.JK", "BLUE.JK",
    "BMAS.JK", "BMBL.JK", "BMHS.JK", "BMSR.JK", "BNBA.JK",
    "BNGA.JK", "BNII.JK", "BNLI.JK", "BOBA.JK", "BOGA.JK",
    "BOLA.JK", "BRNA.JK", "BRRC.JK", "BSIM.JK", "BSML.JK",
    "BSSR.JK", "BTON.JK", "BTPN.JK", "BTPS.JK", "BVIC.JK",
    "BYAN.JK", "CAKK.JK", "CAMP.JK", "CARE.JK", "CARS.JK",
    "CASA.JK", "CASH.JK", "CENT.JK", "CFIN.JK", "CGAS.JK",
    "CHEK.JK", "CHEM.JK", "CHIP.JK", "CINT.JK", "CITA.JK",
    "CITY.JK", "CLAY.JK", "CLEO.JK", "CLPI.JK", "CMNP.JK",
    "CNMA.JK", "CRAB.JK", "CRSN.JK", "CSAP.JK", "CSIS.JK",
    "CSMI.JK", "CTBN.JK", "CTTH.JK", "DADA.JK", "DART.JK",
    "DAYA.JK", "DCII.JK", "DEFI.JK", "DEPO.JK", "DFAM.JK",
    "DGIK.JK", "DGNS.JK", "DGWG.JK", "DILD.JK", "DIVA.JK",
    "DKHH.JK", "DLTA.JK", "DMMX.JK", "DMND.JK", "DNAR.JK",
    "DNET.JK", "DOID.JK", "DOSS.JK", "DPUM.JK", "DRMA.JK",
    "DUTI.JK", "DWGL.JK", "EAST.JK", "ECII.JK", "EDGE.JK",
    "EKAD.JK", "ELPI.JK", "EMDE.JK", "ENAK.JK", "EPMT.JK",
    "ERTX.JK", "ESIP.JK", "ESTA.JK", "ESTI.JK", "EURO.JK",
    "FAPA.JK", "FISH.JK", "FITT.JK", "FLMC.JK", "FMII.JK",
    "FORE.JK", "FORU.JK", "FUJI.JK", "FWCT.JK", "GDST.JK",
    "GDYR.JK", "GEMA.JK", "GEMS.JK", "GGRP.JK", "GHON.JK",
    "GJTL.JK", "GLVA.JK", "GMTD.JK", "GOLD.JK", "GOOD.JK",
    "GPRA.JK", "GPSO.JK", "GRIA.JK", "GRPH.JK", "GSMF.JK",
    "GTBO.JK", "GTRA.JK", "GULA.JK", "GUNA.JK", "GWSA.JK",
    "GZCO.JK", "HAIS.JK", "HAJJ.JK", "HALO.JK", "HBAT.JK",
    "HDFA.JK", "HEAL.JK", "HELI.JK", "HGII.JK", "HILL.JK",
    "HOKI.JK", "HOMI.JK", "IBOS.JK", "IDEA.JK", "IFSH.JK",
    "IKPM.JK", "IMAS.JK", "INAI.JK", "INCI.JK", "INDR.JK",
    "INDS.JK", "INDX.JK", "INOV.JK", "INPP.JK", "INTD.JK",
    "IOTF.JK", "IPAC.JK", "IPCC.JK", "IPOL.JK", "IRRA.JK",
    "ISAP.JK", "ISEA.JK", "ISSP.JK", "ITIC.JK", "JATI.JK",
    "JAWA.JK", "JAYA.JK", "JIHD.JK", "JKON.JK", "JMAS.JK",
    "JRPT.JK", "JSPT.JK", "KAEF.JK", "KAQI.JK", "KBLI.JK",
    "KBLM.JK", "KBLV.JK", "KDSI.JK", "KEJU.JK", "KICI.JK",
    "KING.JK", "KINO.JK", "KIOS.JK", "KJEN.JK", "KKGI.JK",
    "KLIN.JK", "KOBX.JK", "KONI.JK", "KOPI.JK", "KRYA.JK",
    "KSIX.JK", "KUAS.JK", "LABA.JK", "LABS.JK", "LAJU.JK",
    "LAPD.JK", "LINK.JK", "LION.JK", "LIVE.JK", "LOPI.JK",
    "LPCK.JK", "LPPF.JK", "LPPS.JK", "LRNA.JK", "LSIP.JK",
    "LUCK.JK", "LUCY.JK", "MAIN.JK", "MBTO.JK", "MCAS.JK",
    "MCOR.JK", "MDIY.JK", "MDKI.JK", "MDLA.JK", "MDLN.JK",
    "MEDS.JK", "MEGA.JK", "MENN.JK", "MERI.JK", "MERK.JK",
    "MGLV.JK", "MGNA.JK", "MGRO.JK", "MIDI.JK", "MIKA.JK",
    "MINE.JK", "MLPT.JK", "MMLP.JK", "MOLI.JK", "MPIX.JK",
    "MPMX.JK", "MPOW.JK", "MPPA.JK", "MPRO.JK", "MPXL.JK",
    "MRAT.JK", "MSJA.JK", "MSTI.JK", "MTDL.JK", "MUTU.JK",
    "MYOH.JK", "NAIK.JK", "NANO.JK", "NASI.JK", "NATO.JK",
    "NAYZ.JK", "NELY.JK", "NEST.JK", "NICE.JK", "NICK.JK",
    "NIKL.JK", "NISP.JK", "NOBU.JK", "NTBK.JK", "NZIA.JK",
    "OBAT.JK", "OILS.JK", "OKAS.JK", "OLIV.JK", "PALM.JK",
    "PAMG.JK", "PART.JK", "PEGE.JK", "PGLI.JK", "PGUN.JK",
    "PICO.JK", "PLAN.JK", "PMJS.JK", "PMUI.JK", "PNBS.JK",
    "PNGO.JK", "PNIN.JK", "PNSE.JK", "POLU.JK", "PORT.JK",
    "POWR.JK", "PRIM.JK", "PSAT.JK", "PSDN.JK", "PTMP.JK",
    "PTPS.JK", "PTPW.JK", "PTSN.JK", "PTSP.JK", "PUDP.JK",
    "PURI.JK", "PZZA.JK", "RAAM.JK", "RALS.JK", "RANC.JK",
    "RISE.JK", "ROCK.JK", "RONY.JK", "ROTI.JK", "RSCH.JK",
    "RUIS.JK", "RUNS.JK", "SAFE.JK", "SAME.JK", "SAMF.JK",
    "SAPX.JK", "SCCO.JK", "SCNP.JK", "SDMU.JK", "SDPC.JK",
    "SDRA.JK", "SHID.JK", "SHIP.JK", "SIDO.JK", "SILO.JK",
    "SIMP.JK", "SKBM.JK", "SKRN.JK", "SMAR.JK", "SMBR.JK",
    "SOFA.JK", "SOHO.JK", "SONA.JK", "SOTS.JK", "SPRE.JK",
    "SRAJ.JK", "SRSN.JK", "SSMS.JK", "SSTM.JK", "STAA.JK",
    "STAR.JK", "STTP.JK", "SULI.JK", "SUNI.JK", "SURE.JK",
    "SURI.JK", "SWID.JK", "TALF.JK", "TAYS.JK", "TFAS.JK",
    "TIFA.JK", "TIRA.JK", "TLDN.JK", "TMPO.JK", "TNCA.JK",
    "TOOL.JK", "TOTL.JK", "TRIM.JK", "UCID.JK", "UFOE.JK",
    "ULTJ.JK", "UNIC.JK", "UNIT.JK", "UNTD.JK", "UVCR.JK",
    "VAST.JK", "VERN.JK", "VICO.JK", "VINS.JK", "VISI.JK",
    "VOKS.JK", "VRNA.JK", "VTNY.JK", "WAPO.JK", "WEGE.JK",
    "WEHA.JK", "WINS.JK", "WOOD.JK", "YELO.JK", "YOII.JK",
    "YPAS.JK",
]

def get_all_stocks():
    """Return list of all IHSG stocks (Unique)"""
    return sorted(list(set(IHSG_STOCKS)))

def get_stock_count():
    """Return total number of stocks"""
    return len(get_all_stocks())
