# ============================================
# IHSG STOCKS LIST - LIQUID ONLY (~600 saham)
# ============================================
# Filter: hapus zero-volume (suspended/FCA) + turnover < ~150M/hari
# Total: 600 saham
# Format: Yahoo Finance ticker with .JK suffix

IHSG_STOCKS = [
    "RAJA.JK", "RATU.JK", "MINA.JK", "BUVA.JK", "PADI.JK",
    "BNBR.JK", "VKTR.JK", "BRMS.JK", "BUMI.JK", "DEWA.JK",
    "ENRG.JK", "PTRO.JK", "BRPT.JK", "CUAN.JK", "CDIA.JK",
    "TPIA.JK", "BREN.JK", "DSSA.JK", "IMPC.JK", "BIPI.JK",
    "COIN.JK", "SUPA.JK", "MBMA.JK", "ESSA.JK", "ADMR.JK",
    "EMAS.JK", "AADI.JK", "ADRO.JK", "ANTM.JK", "NCKL.JK",
    "INCO.JK", "INDY.JK", "HRUM.JK", "NICL.JK", "ARCI.JK",
    "HRTA.JK", "MBSS.JK", "BULL.JK", "OASA.JK", "KETR.JK",
    "SOCI.JK", "DOOH.JK", "INET.JK", "CBRE.JK", "WIFI.JK",
    "HUMI.JK", "FORE.JK", "BELL.JK", "ZATA.JK", "ASHA.JK",
    "RMKE.JK", "RMKO.JK", "GZCO.JK", "COCO.JK", "DATA.JK",
    "MDIA.JK", "PSKT.JK", "CBDK.JK", "BKSL.JK", "PANI.JK",
    "TRUE.JK", "TRIN.JK", "WIIM.JK", "TINS.JK", "PPRE.JK",
    "APLN.JK", "PYFA.JK", "ASSA.JK", "BUKA.JK", "SCMA.JK",
    "PTBA.JK", "ARKO.JK", "MORA.JK", "GTSI.JK", "NRCA.JK",
    "FILM.JK", "PSAB.JK", "RLCO.JK", "AALI.JK", "ABMM.JK",
    "ACES.JK", "ACRO.JK", "ADES.JK", "ADHI.JK", "ADMF.JK",
    "AGII.JK", "AGRO.JK", "AHAP.JK", "AIMS.JK", "AISA.JK",
    "AKRA.JK", "AKSI.JK", "ALII.JK", "ALKA.JK", "AMMN.JK",
    "AMRT.JK", "APEX.JK", "APIC.JK", "APLI.JK", "AREA.JK",
    "ARII.JK", "ARNA.JK", "ARTO.JK", "ASGR.JK", "ASII.JK",
    "ASLC.JK", "ASLI.JK", "ASPI.JK", "ASPR.JK", "ASRI.JK",
    "ATAP.JK", "AUTO.JK", "AVIA.JK", "AWAN.JK", "AYAM.JK",
    "BABP.JK", "BABY.JK", "BACA.JK", "BAIK.JK", "BAJA.JK",
    "BANK.JK", "BBCA.JK", "BBHI.JK", "BBKP.JK", "BBNI.JK",
    "BBRI.JK", "BBRM.JK", "BBTN.JK", "BBYB.JK", "BCAP.JK",
    "BCIC.JK", "BCIP.JK", "BDKR.JK", "BDMN.JK", "BEEF.JK",
    "BEER.JK", "BEKS.JK", "BELI.JK", "BEST.JK", "BFIN.JK",
    "BGTG.JK", "BHIT.JK", "BINA.JK", "BIPP.JK", "BIRD.JK",
    "BISI.JK", "BJBR.JK", "BJTM.JK", "BKSW.JK", "BLOG.JK",
    "BLTA.JK", "BLUE.JK", "BMBL.JK", "BMHS.JK", "BMRI.JK",
    "BMTR.JK", "BNBA.JK", "BNGA.JK", "BNII.JK", "BNLI.JK",
    "BOAT.JK", "BOBA.JK", "BOGA.JK", "BOLA.JK", "BRIS.JK",
    "BRRC.JK", "BSBK.JK", "BSDE.JK", "BSML.JK", "BSSR.JK",
    "BTEK.JK", "BTPS.JK", "BUKK.JK", "BVIC.JK", "BWPT.JK",
    "BYAN.JK", "CARE.JK", "CARS.JK", "CASA.JK", "CASH.JK",
    "CASS.JK", "CBUT.JK", "CEKA.JK", "CENT.JK", "CFIN.JK",
    "CGAS.JK", "CHEK.JK", "CHEM.JK", "CITA.JK", "CITY.JK",
    "CLEO.JK", "CLPI.JK", "CMNT.JK", "CMRY.JK", "CNKO.JK",
    "CNMA.JK", "COAL.JK", "CPIN.JK", "CPRO.JK", "CRAB.JK",
    "CSIS.JK", "CSMI.JK", "CSRA.JK", "CTBN.JK", "CTRA.JK",
    "CTTH.JK", "CYBR.JK", "DAAZ.JK", "DCII.JK", "DEFI.JK",
    "DEWI.JK", "DFAM.JK", "DGIK.JK", "DGNS.JK", "DGWG.JK",
    "DILD.JK", "DIVA.JK", "DKFT.JK", "DKHH.JK", "DLTA.JK",
    "DMAS.JK", "DNAR.JK", "DNET.JK", "DOID.JK", "DPUM.JK",
    "DRMA.JK", "DSFI.JK", "DSNG.JK", "DWGL.JK", "DYAN.JK",
    "ELIT.JK", "ELPI.JK", "ELSA.JK", "ELTY.JK", "EMDE.JK",
    "EMTK.JK", "ENAK.JK", "ENZO.JK", "EPAC.JK", "EPMT.JK",
    "ERAA.JK", "ERAL.JK", "ERTX.JK", "ESIP.JK", "ESTI.JK",
    "EURO.JK", "EXCL.JK", "FAST.JK", "FIRE.JK", "FITT.JK",
    "FLMC.JK", "FOLK.JK", "FORU.JK", "FPNI.JK", "FUJI.JK",
    "FUTR.JK", "FWCT.JK", "GEMS.JK", "GGRM.JK", "GGRP.JK",
    "GHON.JK", "GIAA.JK", "GJTL.JK", "GMFI.JK", "GOLF.JK",
    "GOTO.JK", "GPRA.JK", "GPSO.JK", "GRIA.JK", "GRPH.JK",
    "GRPM.JK", "GSMF.JK", "GULA.JK", "GUNA.JK", "GWSA.JK",
    "HAJJ.JK", "HALO.JK", "HATM.JK", "HBAT.JK", "HDFA.JK",
    "HDIT.JK", "HEAL.JK", "HERO.JK", "HEXA.JK", "HILL.JK",
    "HMSP.JK", "HOKI.JK", "HOMI.JK", "HOPE.JK", "IATA.JK",
    "IBOS.JK", "ICBP.JK", "ICON.JK", "IDEA.JK", "IKAI.JK",
    "IKAN.JK", "IMAS.JK", "IMJS.JK", "INDF.JK", "INDO.JK",
    "INDS.JK", "INDX.JK", "INKP.JK", "INOV.JK", "INPC.JK",
    "INTP.JK", "IOTF.JK", "IPCC.JK", "IPCM.JK", "IPOL.JK",
    "IPTV.JK", "IRRA.JK", "IRSX.JK", "ISAP.JK", "ISAT.JK",
    "ISEA.JK", "ISSP.JK", "ITMA.JK", "ITMG.JK", "JARR.JK",
    "JAST.JK", "JATI.JK", "JAWA.JK", "JAYA.JK", "JECC.JK",
    "JGLE.JK", "JIHD.JK", "JKON.JK", "JMAS.JK", "JPFA.JK",
    "JRPT.JK", "JSMR.JK", "JTPE.JK", "KAEF.JK", "KAQI.JK",
    "KBAG.JK", "KBLV.JK", "KDTN.JK", "KEEN.JK", "KEJU.JK",
    "KIJA.JK", "KIOS.JK", "KJEN.JK", "KKGI.JK", "KLAS.JK",
    "KLBF.JK", "KOBX.JK", "KOCI.JK", "KOKA.JK", "KOPI.JK",
    "KOTA.JK", "KPIG.JK", "KRAS.JK", "KREN.JK", "KRYA.JK",
    "KUAS.JK", "LABA.JK", "LABS.JK", "LAJU.JK", "LAND.JK",
    "LAPD.JK", "LCKM.JK", "LEAD.JK", "LIVE.JK", "LOPI.JK",
    "LPCK.JK", "LPKR.JK", "LPPF.JK", "LSIP.JK", "LUCK.JK",
    "LUCY.JK", "MAHA.JK", "MAIN.JK", "MANG.JK", "MAPA.JK",
    "MAPI.JK", "MARK.JK", "MAYA.JK", "MCAS.JK", "MCOL.JK",
    "MCOR.JK", "MDIY.JK", "MDKA.JK", "MDLA.JK", "MDLN.JK",
    "MEDC.JK", "MEDS.JK", "MEGA.JK", "MEJA.JK", "MERK.JK",
    "MGLV.JK", "MGNA.JK", "MGRO.JK", "MHKI.JK", "MIDI.JK",
    "MIKA.JK", "MINE.JK", "MITI.JK", "MKAP.JK", "MKPI.JK",
    "MLBI.JK", "MLPL.JK", "MLPT.JK", "MMIX.JK", "MMLP.JK",
    "MNCN.JK", "MOLI.JK", "MPIX.JK", "MPMX.JK", "MPOW.JK",
    "MPPA.JK", "MSIE.JK", "MSIN.JK", "MSJA.JK", "MSKY.JK",
    "MSTI.JK", "MTDL.JK", "MTEL.JK", "MTFN.JK", "MUTU.JK",
    "MYOR.JK", "NAIK.JK", "NANO.JK", "NASI.JK", "NATO.JK",
    "NAYZ.JK", "NELY.JK", "NEST.JK", "NETV.JK", "NIKL.JK",
    "NINE.JK", "NIRO.JK", "NISP.JK", "NOBU.JK", "NPGF.JK",
    "NSSS.JK", "NTBK.JK", "NZIA.JK", "OBAT.JK", "OBMD.JK",
    "OILS.JK", "OKAS.JK", "OLIV.JK", "OMED.JK", "OPMS.JK",
    "PACK.JK", "PADA.JK", "PALM.JK", "PAMG.JK", "PANS.JK",
    "PART.JK", "PBID.JK", "PBRX.JK", "PBSA.JK", "PEGE.JK",
    "PGAS.JK", "PGEO.JK", "PGUN.JK", "PIPA.JK", "PJHB.JK",
    "PKPK.JK", "PLAN.JK", "PMUI.JK", "PNBN.JK", "PNBS.JK",
    "PNIN.JK", "PNLF.JK", "POLA.JK", "POWR.JK", "PPGL.JK",
    "PPRI.JK", "PPRO.JK", "PRDA.JK", "PRIM.JK", "PSDN.JK",
    "PTMP.JK", "PTPP.JK", "PTPS.JK", "PTPW.JK", "PTSN.JK",
    "PURA.JK", "PURI.JK", "PWON.JK", "RAAM.JK", "RALS.JK",
    "RBMS.JK", "RCCC.JK", "REAL.JK", "RGAS.JK", "RICY.JK",
    "RISE.JK", "ROCK.JK", "RODA.JK", "ROTI.JK", "RSCH.JK",
    "SAFE.JK", "SAME.JK", "SATU.JK", "SCNP.JK", "SDMU.JK",
    "SDRA.JK", "SGER.JK", "SGRO.JK", "SICO.JK", "SIDO.JK",
    "SILO.JK", "SIMP.JK", "SINI.JK", "SKBM.JK", "SLIS.JK",
    "SMAR.JK", "SMBR.JK", "SMDR.JK", "SMGA.JK", "SMGR.JK",
    "SMIL.JK", "SMKM.JK", "SMLE.JK", "SMMA.JK", "SMMT.JK",
    "SMRA.JK", "SMSM.JK", "SNLK.JK", "SOFA.JK", "SOLA.JK",
    "SOTS.JK", "SPRE.JK", "SPTO.JK", "SRAJ.JK", "SRSN.JK",
    "SRTG.JK", "SSIA.JK", "SSMS.JK", "SSTM.JK", "STAA.JK",
    "STAR.JK", "STRK.JK", "SULI.JK", "SUNI.JK", "SURE.JK",
    "SURI.JK", "TALF.JK", "TAMA.JK", "TAPG.JK", "TAXI.JK",
    "TBIG.JK", "TBLA.JK", "TCPI.JK", "TEBE.JK", "TIRA.JK",
    "TIRT.JK", "TKIM.JK", "TLDN.JK", "TLKM.JK", "TMAS.JK",
    "TMPO.JK", "TOBA.JK", "TOOL.JK", "TOSK.JK", "TOTL.JK",
    "TOTO.JK", "TOWR.JK", "TPMA.JK", "TRON.JK", "TSPC.JK",
    "TUGU.JK", "UANG.JK", "UCID.JK", "UDNG.JK", "ULTJ.JK",
    "UNIC.JK", "UNIQ.JK", "UNSP.JK", "UNTD.JK", "UNTR.JK",
    "UNVR.JK", "UVCR.JK", "VAST.JK", "VERN.JK", "VICI.JK",
    "VISI.JK", "VIVA.JK", "VTNY.JK", "WBSA.JK", "WEGE.JK",
    "WEHA.JK", "WGSH.JK", "WIDI.JK", "WINR.JK", "WINS.JK",
    "WIRG.JK", "WMPP.JK", "WMUU.JK", "WOOD.JK", "WOWS.JK",
    "WSBP.JK", "WTON.JK", "YELO.JK", "YOII.JK", "ZONE.JK",
]

def get_all_stocks():
    """Return list of all IHSG stocks (Unique)"""
    return sorted(list(set(IHSG_STOCKS)))

def get_stock_count():
    """Return total number of stocks"""
    return len(get_all_stocks())
